"""category_type

Revision ID: 861988020a4c
Revises: e500420d5d25
Create Date: 2026-06-15 23:27:27.666326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '861988020a4c'
down_revision: Union[str, Sequence[str], None] = 'e500420d5d25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('categories')
    op.alter_column('tasks', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'tasks', 'categories', ['category_id'], ['id'])
    op.alter_column('tasks', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_table('categories',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Categories')
    # ### end Alembic commands ###
